project_id = "kcxhsmlqqyarhlmcapmj"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://c8fabd7a-96c7-4aff-8d7b-001690ec23c7.lovableproject.com"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.get-billing-info]
verify_jwt = true

[functions.cancel-subscription]
verify_jwt = true

[functions.fetch-commodity-prices]
verify_jwt = false

[functions.fetch-commodity-data]
verify_jwt = false